options:
  base-point: 5000
  max-point: 10000
  check-point: 100
  time-check: 3600

items:
  '0':
    material: wheat3
    amount: 16
    base-value: 100
  '1':
    material: sugarcane3
    amount: 16
    base-value: 120
  '2':
    material: CARROT
    amount: 16
    base-value: 140
  '3':
    material: POTATO
    amount: 16
    base-value: 160
  '4':
    material: BEETROOT
    amount: 16
    base-value: 180
  '5':
    material: MELON
    amount: 16
    base-value: 200
  '6':
    material: PUMPKIN
    amount: 16
    base-value: 220
  '7':
    material: SWEET_BERRIES
    amount: 16
    base-value: 240
  '8':
    material: CACTUS
    amount: 16
    base-value: 260
