name: Market
version: ${project.version}
main: me.manaki.plugin.market.Market
api-version: 1.16
depend: [ Vault ]
softdepend: [ Shops, LangUtils ]
commands:
  market:
    description: Mở shop bán
    aliases:
      - thuonglai
      - markets
      - cho
